[package]
name = "adapter"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
wasmer = "4.0.0"
wasmtime = { git = "https://github.com/bytecodealliance/wasmtime", features = ["component-model"] }
